### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by RickCarlino** [orbitalimpact/opal-phaser#15]
Sorry if you guys already knew. I just tried clicking the homepage link and got a Heroku application error.

**Comment by ylluminarious** [comment]
@RickCarlino Yes, thanks, we were already aware. I meant to fix it this past weekend, but something came up and I was unable to work on it. Thanks again; we'll try to get it back up ASAP.

**Comment by ylluminarious** [comment]
@RickCarlino The site's back up now; it was just a bug with having to update the MongoDB driver with VoltRb.
