### ISSUE TITLE
Change Game#initialize to take a single hash options parameter

### ISSUE THREAD

**Issue by andrew-carroll** [orbitalimpact/opal-phaser#8]
There are too many parameters to remember in Game#initialize. It's not immediately obvious what `Phaser::Game.new(800, 600, Phaser::AUTO, 'example', state)` means. We should make the parameters explicit and order-independent by supplying an options hash instead, e.g. `Game.new(width: 800, height: 600, state: state,` etc.

Thoughts?

**Comment by gabrielrios** [comment]
I don't like it either and don't see any reason for not to change it to use
a hash. I've done like this just as a quick start and following how
phaser.js works, it was literally the first line of code. The kind of thing
that you do thinking about going back to change but end up forgetting.

On Sun, Mar 1, 2015 at 5:46 PM, Andrew Carroll <notifications@github.com>
wrote:

> There are too many parameters to remember in Game#initialize. It's not
> immediately obvious what Phaser::Game.new(800, 600, Phaser::AUTO,
> 'example', state) means. We should make the parameters explicit and
> order-independent by supplying an options hash instead, e.g. Game.new(width:
> 800, height: 600, state: state, etc.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orbitalimpact/opal-phaser/issues/8>.
>



-- 
Gabriel Rios
+55 75 9129 6322
http://g <http://about.me/gabrielrios>abrielrios.me

**Comment by ylluminarious** [comment]
Yes, I think this is a good idea. It will definitely be more clear as to what each parameter is for. I can implement it if you aren't already doing it, @gabrielrios.

**Comment by gabrielrios** [comment]
go ahead and do it @ylluminarious

**Comment by ylluminarious** [comment]
@andrew-carroll I've fixed this issue, but so far only on the `demo` branch.
https://github.com/orbitalimpact/opal-phaser/commit/1f5d25052ef54ae212ff4db179453571766f4d45
When we merge `master` and `demo`, the issue will be fixed so we'll try to hurry up on that.

**Comment by andreanastacio** [comment]
Fixed on #7
