### ISSUE TITLE
Problems with the way that files are currently loading

### ISSUE THREAD

**Issue by ylluminarious** [orbitalimpact/opal-phaser#9]
@andreanastacio @gabrielrios @ylluminate Today I was working on opal-phaser again, trying to finish up a game that will hopefully help market opal-phaser. Unfortunately, I've been having some problems with the way that files are loaded in opal-phaser right now. i.e. https://github.com/orbitalimpact/opal-phaser/blob/master/lib/opal/phaser/setup.rb
The way that these files are loading is currently not letting you access certain classes that get loaded after the class that you're working from. For example, I was going to change the [`create` alias the in Group class](https://github.com/orbitalimpact/opal-phaser/blob/master/lib/opal/phaser/core/group.rb#L12) to be [like this](https://gist.github.com/da108ac0fabeae45f045), but the Group class gets loaded before Sprite, as you can see [here](https://github.com/orbitalimpact/opal-phaser/blob/master/lib/opal/phaser/setup.rb#L5). So, I am having trouble doing this currently. This seems like it will be a recurring problem in the future, so I think we should make the files load in a way that will solve this problem.

**Comment by andreanastacio** [comment]
i'll try some thing this weekend

**Comment by ylluminarious** [comment]
@andreanastacio Alright, thanks.

**Comment by gabrielrios** [comment]
I think you just need to direct require the needed files by each class, if done it on: https://github.com/orbitalimpact/opal-phaser/commit/d6ba0f69c31b8cf6c673acd9f272bc86416f0b2e

**Comment by ylluminarious** [comment]
@gabrielrios Yes, this seems to work.
@andreanastacio I guess this is resolved, so you don't have to try and fix this, thanks though :)
